[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing (important for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 